In [43]:
import pandas as pd
from datetime import datetime
import io
import numpy as np

In [44]:
def process_date(date_string_series):
    # Handle MM/DD/YYYY, YYYY/MM/DD, and YYYY-MM-DD date formats
    parsed_dates = pd.to_datetime(date_string_series, format='%m/%d/%Y', errors='coerce')
    parsed_dates = parsed_dates.fillna(pd.to_datetime(date_string_series, format='%Y/%m/%d', errors='coerce'))
    parsed_dates = parsed_dates.fillna(pd.to_datetime(date_string_series, format='%Y-%m-%d', errors='coerce'))

    if parsed_dates.isna().any():
        invalid_examples = date_string_series[parsed_dates.isna()].head(5).tolist()
        raise ValueError(f"Unrecognized date format found: {invalid_examples}")

    return parsed_dates.dt.strftime('%Y年%m月%d日')

In [45]:
df_input = pd.read_csv('accountactivity-2.csv')

In [46]:
columns_exp = ['日期', '类型', '金额', '一级分类', '二级分类', '账户1', '账户2', '备注', '货币', '标签']
df_exp = pd.DataFrame(columns=columns_exp)

In [47]:
columns_TD = ["Date", "Description", "Amount_1", "Amount_2", "Balance"]
df_input.columns = columns_TD

In [48]:
# account_mapping = {"TD CASH BACK VISA* CARD":308, "TD EVERY DAY SAVINGS ACCOUNT":995, "TD UNLIMITED CHEQUING ACCOUNT":995 }
# transaction_mapping = {"Income":"收入", "Interest Income":"收入",}
category_mapping = {
    'FRESHCO': ['Grocery'],
    'APPLE STORE': ['数码', '电子产品'],
    'APPLE.COM': ['数码', '应用软件'],
    'APPLE': ['数码', '软件'],
    'COCO FRESH TEA': ['餐饮', '饮品'],
    'DAMIAN WARNER': ['运动', '健身'],
    'EMPL INS': ['收入', 'EI'],
    'EUREST': ['餐饮', 'work'],
    'FARM BOY': ['Grocery'],
    'FIDO MOBILE': ['Phone Bill'],
    'IMMIGRATION CANADA': ['政府服务', '移民申请'],
    'JUQU EDUCATION': ['教育', '学费'],
    'JAPANESE CANADI': ['餐饮', '活动餐食'],
    'POPARIDE': ['交通', '拼车'],
    'PREAUTHORIZED PAYMENT': ['转账', '还款'],
    'REXALL PHARMACY': ['购物', '药妆'],
    'SEND E/TFR': ['转账', '电子转账'],
    'SQ *GUSHI EVENT': ['餐饮', '活动'],
    'SQ *NATURALJAPA': ['餐饮', '活动'],
    'SQ *OMUSUBI BAR': ['餐饮', '活动'],
    'SQ *YURURI CRAF': ['餐饮', '活动'],
    'TCKTWEB*HINAMATSURI202': ['娱乐', '门票'],
    'TD MHA PPP': ['转账', '账户转移'],
    'TD VISA PREAUTH PYMT': ['转账', '信用卡还款'],
    'UBER CANADA/UBEREATS': ['餐饮', '外卖'],
    'UBER CANADA/UBERTRIP': ['交通', '打车'],
    'WOBO.AI': ['数码', '应用软件'],
    '*RFBT/MARKVILLE MALL': ['购物', '商场'],
    'LUCY': ['餐饮', 'dine in'],
    'SHOPPERS DRUG': ['购物'],
    'MCDONALD': ['餐饮', 'dine in'],
    'MARSHALLS/HOMES': ['购物', '日用'],
    'MEAL': ['餐饮', 'dine in'],
    'WESTERN DRUG MART': ['购物'],
    'IVEY BUSINESS SCHOOL': ['餐饮', 'dine in'],
    'SEPHORA': ['护肤'],
    'TEMU': ['购物'],
    'URBAN PLANET': ['购物'],
    'COCA COLA': ['餐饮', '零食'],
    'OPENAI': ['数码', '应用软件'],
    'WHOLE FOODS': ['Grocery'],
    'XIANG ZI': ['餐饮', 'dine in'],
    'GOOD CATCH BAR': ['餐饮', 'dine in'],
    'UBER': ['交通', '打车'],
    'PROVIDENT ENERG': ['住房', '水电费'],
    'SQUARE ONE INS': ['住房', '住房保险'],
    'AMZN MKTP CA': ['购物'],
    'HERO TEA LONDON': ['餐饮', '饮品'],
    'SQ *PISTACHIOS ? QUALITY': ['餐饮', '零食'],
    'LONDON MUSLIM MOSQUE': ['慈善', '宗教捐赠'],
    'TST-THAIFOON DOWNTOWN': ['餐饮', '泰餐'],
    'LONDON TRANSIT COMMISS': ['交通', '公交'],
    'TWINS LOUNGE': ['餐饮', '酒吧'],
    'M&M FOOD MARKET #036': ['Grocery'],
    "ANGELO'S ITALIAN MARKE": ['Grocery'],
    'BELL CANADA (OB)': ['Phone Bill'],
    'SQ *TC TRADE GOSQ.COM': ['购物', '二手交易'],
    'SEND E-TFR': ['转账', '电子转账'],
    'MONTHLY ACCOUNT FEE': ['银行', '账户管理费'],
    'ACCT BAL REBATE': ['银行', '账户返利'],
    'BLACK WALNUT BA': ['餐饮', '甜品'],
    "SQ *HAVEN'S CRE": ['餐饮', '甜品']
}

df_exp['一级分类'] = df_input['Description'].apply(
    lambda x: next((category_mapping[key][0] for key in category_mapping.keys() if key in str(x).upper()), None)
 )
df_exp['二级分类'] = df_input['Description'].apply(
    lambda x: next((category_mapping[key][1] for key in category_mapping.keys() if key in str(x).upper() and len(category_mapping[key]) > 1), None)
 )

In [49]:
# 1. Create a "mask" (a list of True/False) for rows containing the string
# case=False makes it catch "td mha" or "TD MHA"
mask = df_input['Description'].str.contains("TD MHA", case=False, na=False)

# 2. Update multiple columns for those specific rows in one go
df_exp.loc[mask, ['类型', '账户1', '账户2']] = ["转账", "995", "375"]

In [50]:
df_exp

     日期   类型   金额        一级分类   二级分类  账户1  账户2   备注   货币   标签
0   NaN  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
1   NaN  NaN  NaN          转账     还款  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN          餐饮     零食  NaN  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN          购物     药妆  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN          慈善   宗教捐赠  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  NaN          餐饮     泰餐  NaN  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
11  NaN  NaN  NaN          交通     公交  NaN  NaN  NaN  NaN  NaN
12  NaN  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
14  NaN  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
15  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
18  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
19  NaN  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
20  NaN  NaN  NaN  Phone Bill    NaN  NaN  NaN  NaN  NaN  NaN
21  NaN  NaN  NaN          购物   二手交易  NaN  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
23  NaN  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
24  NaN  NaN  NaN          收入     EI  NaN  NaN  NaN  NaN  NaN
25  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN          转账   电子转账  NaN  NaN  NaN  NaN  NaN
27  NaN  NaN  NaN          住房    水电费  NaN  NaN  NaN  NaN  NaN
28  NaN  NaN  NaN          转账   电子转账  NaN  NaN  NaN  NaN  NaN
29  NaN  NaN  NaN          餐饮     甜品  NaN  NaN  NaN  NaN  NaN
30  NaN  NaN  NaN          餐饮     甜品  NaN  NaN  NaN  NaN  NaN
31  NaN  NaN  NaN          住房    水电费  NaN  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN          运动     健身  NaN  NaN  NaN  NaN  NaN
33  NaN   转账  NaN          转账   账户转移  995  375  NaN  NaN  NaN
34  NaN   转账  NaN          转账   账户转移  995  375  NaN  NaN  NaN
35  NaN  NaN  NaN          转账  信用卡还款  NaN  NaN  NaN  NaN  NaN
36  NaN  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN
37  NaN  NaN  NaN          收入     EI  NaN  NaN  NaN  NaN  NaN
38  NaN  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN
39  NaN  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN

In [51]:


# This covers both actual empty strings and null/NaN values
df_exp['一级分类'] = df_exp['一级分类'].replace(['', np.nan, None], '餐饮')

In [52]:
df_exp

     日期   类型   金额        一级分类   二级分类  账户1  账户2   备注   货币   标签
0   NaN  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
1   NaN  NaN  NaN          转账     还款  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN          餐饮     零食  NaN  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN          购物     药妆  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN          慈善   宗教捐赠  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  NaN          餐饮     泰餐  NaN  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
11  NaN  NaN  NaN          交通     公交  NaN  NaN  NaN  NaN  NaN
12  NaN  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
14  NaN  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
15  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
18  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
19  NaN  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
20  NaN  NaN  NaN  Phone Bill    NaN  NaN  NaN  NaN  NaN  NaN
21  NaN  NaN  NaN          购物   二手交易  NaN  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
23  NaN  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
24  NaN  NaN  NaN          收入     EI  NaN  NaN  NaN  NaN  NaN
25  NaN  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN          转账   电子转账  NaN  NaN  NaN  NaN  NaN
27  NaN  NaN  NaN          住房    水电费  NaN  NaN  NaN  NaN  NaN
28  NaN  NaN  NaN          转账   电子转账  NaN  NaN  NaN  NaN  NaN
29  NaN  NaN  NaN          餐饮     甜品  NaN  NaN  NaN  NaN  NaN
30  NaN  NaN  NaN          餐饮     甜品  NaN  NaN  NaN  NaN  NaN
31  NaN  NaN  NaN          住房    水电费  NaN  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN          运动     健身  NaN  NaN  NaN  NaN  NaN
33  NaN   转账  NaN          转账   账户转移  995  375  NaN  NaN  NaN
34  NaN   转账  NaN          转账   账户转移  995  375  NaN  NaN  NaN
35  NaN  NaN  NaN          转账  信用卡还款  NaN  NaN  NaN  NaN  NaN
36  NaN  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN
37  NaN  NaN  NaN          收入     EI  NaN  NaN  NaN  NaN  NaN
38  NaN  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN
39  NaN  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN

In [53]:
# Parse mixed date formats in the source file: MM/DD/YYYY, YYYY/MM/DD, and YYYY-MM-DD
parsed_dates = pd.to_datetime(df_input['Date'], format='%m/%d/%Y', errors='coerce')
parsed_dates = parsed_dates.fillna(pd.to_datetime(df_input['Date'], format='%Y/%m/%d', errors='coerce'))
parsed_dates = parsed_dates.fillna(pd.to_datetime(df_input['Date'], format='%Y-%m-%d', errors='coerce'))

if parsed_dates.isna().any():
    invalid_examples = df_input.loc[parsed_dates.isna(), 'Date'].head(5).tolist()
    raise ValueError(f"Unrecognized date format found in Date column: {invalid_examples}")

df_input['Date'] = parsed_dates
df_exp['日期'] = df_input['Date'].dt.strftime('%Y年%m月%d日')

In [54]:
df_exp

             日期   类型   金额        一级分类   二级分类  账户1  账户2   备注   货币   标签
0   2026年04月08日  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
1   2026年04月06日  NaN  NaN          转账     还款  NaN  NaN  NaN  NaN  NaN
2   2026年04月05日  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
3   2026年04月05日  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
4   2026年04月05日  NaN  NaN          餐饮     零食  NaN  NaN  NaN  NaN  NaN
5   2026年04月04日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
6   2026年04月04日  NaN  NaN          购物     药妆  NaN  NaN  NaN  NaN  NaN
7   2026年04月03日  NaN  NaN          慈善   宗教捐赠  NaN  NaN  NaN  NaN  NaN
8   2026年04月03日  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
9   2026年04月02日  NaN  NaN          餐饮     泰餐  NaN  NaN  NaN  NaN  NaN
10  2026年04月01日  NaN  NaN          交通     打车  NaN  NaN  NaN  NaN  NaN
11  2026年04月01日  NaN  NaN          交通     公交  NaN  NaN  NaN  NaN  NaN
12  2026年03月31日  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
13  2026年03月31日  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
14  2026年03月31日  NaN  NaN          餐饮     酒吧  NaN  NaN  NaN  NaN  NaN
15  2026年03月29日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
16  2026年03月29日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
17  2026年03月28日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
18  2026年03月28日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
19  2026年03月27日  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
20  2026年03月26日  NaN  NaN  Phone Bill    NaN  NaN  NaN  NaN  NaN  NaN
21  2026年03月25日  NaN  NaN          购物   二手交易  NaN  NaN  NaN  NaN  NaN
22  2026年03月16日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
23  2026年03月16日  NaN  NaN          餐饮     外卖  NaN  NaN  NaN  NaN  NaN
24  2026年03月24日  NaN  NaN          收入     EI  NaN  NaN  NaN  NaN  NaN
25  2026年03月24日  NaN  NaN     Grocery    NaN  NaN  NaN  NaN  NaN  NaN
26  2026年03月26日  NaN  NaN          转账   电子转账  NaN  NaN  NaN  NaN  NaN
27  2026年03月27日  NaN  NaN          住房    水电费  NaN  NaN  NaN  NaN  NaN
28  2026年04月01日  NaN  NaN          转账   电子转账  NaN  NaN  NaN  NaN  NaN
29  2026年04月06日  NaN  NaN          餐饮     甜品  NaN  NaN  NaN  NaN  NaN
30  2026年04月06日  NaN  NaN          餐饮     甜品  NaN  NaN  NaN  NaN  NaN
31  2026年04月06日  NaN  NaN          住房    水电费  NaN  NaN  NaN  NaN  NaN
32  2026年04月06日  NaN  NaN          运动     健身  NaN  NaN  NaN  NaN  NaN
33  2026年04月06日   转账  NaN          转账   账户转移  995  375  NaN  NaN  NaN
34  2026年04月06日   转账  NaN          转账   账户转移  995  375  NaN  NaN  NaN
35  2026年04月06日  NaN  NaN          转账  信用卡还款  NaN  NaN  NaN  NaN  NaN
36  2026年04月09日  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN
37  2026年04月10日  NaN  NaN          收入     EI  NaN  NaN  NaN  NaN  NaN
38  2026年04月13日  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN
39  2026年04月15日  NaN  NaN          数码   应用软件  NaN  NaN  NaN  NaN  NaN

In [55]:
# Initialize columns
df_exp['金额'] = df_input['Amount_2']
df_exp['类型'] = "收入"

# Update rows where Amount_1 has data
mask = (df_input['Amount_1'].fillna('') != '')
df_exp.loc[mask, '金额'] = df_input['Amount_1']
df_exp.loc[mask, '类型'] = "支出"

In [56]:
df_exp['备注'] = df_input['Description']
# df_exp['金额'] = df_input['Amount']
# df_exp['类型'] = df_input['Category'].map(transaction_mapping)
# df_exp['类型'].fillna("支出", inplace=True)
# df_exp['账户1'] = df_input['Account Name'].map(account_mapping)

df_exp['货币'] = 'CAD'

In [57]:
df_exp.to_csv('export.csv', index=False)

In [58]:
df_exp

,日期,类型,金额,一级分类,二级分类,账户1,账户2,备注,货币,标签
0,2026年04月08日,支出,66.35,餐饮,外卖,NaN,NaN,UBER CANADA/UBEREATS,CAD,NaN
1,2026年04月06日,收入,811.46,转账,还款,NaN,NaN,PREAUTHORIZED PAYMENT,CAD,NaN
2,2026年04月05日,支出,5.91,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
3,2026年04月05日,支出,6.28,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
4,2026年04月05日,支出,44.38,餐饮,零食,NaN,NaN,SQ *PISTACHIOS ? QUALITY,CAD,NaN
5,2026年04月04日,支出,6.97,Grocery,NaN,NaN,NaN,FARM BOY #93,CAD,NaN
6,2026年04月04日,支出,17.28,购物,药妆,NaN,NaN,REXALL PHARMACY #1790,CAD,NaN
7,2026年04月03日,支出,1.00,慈善,宗教捐赠,NaN,NaN,LONDON MUSLIM MOSQUE,CAD,NaN
8,2026年04月03日,支出,8.79,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
9,2026年04月02日,支出,51.67,餐饮,泰餐,NaN,NaN,TST-Thaifoon Downtown,CAD,NaN
10,2026年04月01日,支出,14.15,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
11,2026年04月01日,支出,50.00,交通,公交,NaN,NaN,LONDON TRANSIT COMMISS,CAD,NaN
12,2026年03月31日,支出,3.96,餐饮,酒吧,NaN,NaN,TWINS LOUNGE,CAD,NaN
13,2026年03月31日,支出,15.26,餐饮,酒吧,NaN,NaN,TWINS LOUNGE,CAD,NaN
14,2026年03月31日,支出,5.09,餐饮,酒吧,NaN,NaN,TWINS LOUNGE,CAD,NaN
15,2026年03月29日,支出,9.02,Grocery,NaN,NaN,NaN,M&M FOOD MARKET #036,CAD,NaN
16,2026年03月29日,支出,15.81,Grocery,NaN,NaN,NaN,ANGELO'S ITALIAN MARKE,CAD,NaN
17,2026年03月28日,支出,14.68,Grocery,NaN,NaN,NaN,FARM BOY #93,CAD,NaN
18,2026年03月28日,支出,23.12,Grocery,NaN,NaN,NaN,FARM BOY #93,CAD,NaN
19,2026年03月27日,支出,57.07,餐饮,外卖,NaN,NaN,UBER CANADA/UBEREATS,CAD,NaN
20,2026年03月26日,支出,64.42,Phone Bill,NaN,NaN,NaN,BELL CANADA (OB),CAD,NaN
21,2026年03月25日,支出,18.07,购物,二手交易,NaN,NaN,SQ *TC TRADE GOSQ.COM,CAD,NaN
22,2026年03月16日,支出,84.10,Grocery,NaN,NaN,NaN,FARM BOY #93,CAD,NaN
23,2026年03月16日,支出,66.98,餐饮,外卖,NaN,NaN,UBER CANADA/UBEREATS,CAD,NaN
24,2026年03月24日,收入,1398.00,收入,EI,NaN,NaN,EMPL INS EI,CAD,NaN
25,2026年03月24日,支出,10.16,Grocery,NaN,NaN,NaN,FARM BOY #93 _M,CAD,NaN
26,2026年03月26日,支出,30.00,转账,电子转账,NaN,NaN,SEND E-TFR ***8V3,CAD,NaN
27,2026年03月27日,支出,40.04,住房,水电费,NaN,NaN,PROVIDENT ENERG BPY,CAD,NaN
28,2026年04月01日,支出,700.00,转账,电子转账,NaN,NaN,SEND E-TFR ***d4n,CAD,NaN
29,2026年04月06日,支出,5.20,餐饮,甜品,NaN,NaN,BLACK WALNUT BA _M,CAD,NaN
30,2026年04月06日,支出,14.69,餐饮,甜品,NaN,NaN,SQ *HAVEN'S CRE _M,CAD,NaN
31,2026年04月06日,支出,6.99,住房,水电费,NaN,NaN,PROVIDENT ENERG BPY,CAD,NaN
32,2026年04月06日,支出,29.32,运动,健身,NaN,NaN,Damian Warner F FEE,CAD,NaN
33,2026年04月06日,支出,100.00,转账,账户转移,995,375,TD MHA PPP INV,CAD,NaN
34,2026年04月06日,支出,100.00,转账,账户转移,995,375,TD MHA PPP INV,CAD,NaN
35,2026年04月06日,支出,811.46,转账,信用卡还款,NaN,NaN,TD VISA PREAUTH PYMT,CAD,NaN
36,2026年04月09日,支出,2.25,数码,应用软件,NaN,NaN,APPLE.COM/BILL _V,CAD,NaN
37,2026年04月10日,收入,1398.00,收入,EI,NaN,NaN,EMPL INS EI,CAD,NaN
38,2026年04月13日,支出,12.42,数码,应用软件,NaN,NaN,APPLE.COM/BILL _V,CAD,NaN
39,2026年04月15日,支出,1.46,数码,应用软件,NaN,NaN,APPLE.COM/BILL _V,CAD,NaN