In [17]:
import pandas as pd
from datetime import datetime
import io
import numpy as np

In [18]:
def process_date(date_string_series):
    # Handle MM/DD/YYYY, YYYY/MM/DD, and YYYY-MM-DD date formats
    parsed_dates = pd.to_datetime(date_string_series, format='%m/%d/%Y', errors='coerce')
    parsed_dates = parsed_dates.fillna(pd.to_datetime(date_string_series, format='%Y/%m/%d', errors='coerce'))
    parsed_dates = parsed_dates.fillna(pd.to_datetime(date_string_series, format='%Y-%m-%d', errors='coerce'))

    if parsed_dates.isna().any():
        invalid_examples = date_string_series[parsed_dates.isna()].head(5).tolist()
        raise ValueError(f"Unrecognized date format found: {invalid_examples}")

    return parsed_dates.dt.strftime('%Y年%m月%d日')

In [19]:
df_input = pd.read_csv('accountactivity.csv')

In [20]:
columns_exp = ['日期', '类型', '金额', '一级分类', '二级分类', '账户1', '账户2', '备注', '货币', '标签']
df_exp = pd.DataFrame(columns=columns_exp)

In [21]:
columns_TD = ["Date", "Description", "Amount_1", "Amount_2", "Balance"]
df_input.columns = columns_TD

In [22]:
# account_mapping = {"TD CASH BACK VISA* CARD":308, "TD EVERY DAY SAVINGS ACCOUNT":995, "TD UNLIMITED CHEQUING ACCOUNT":995 }
# transaction_mapping = {"Income":"收入", "Interest Income":"收入",}
category_mapping = {
    'FRESHCO': ['Grocery'],
    'APPLE STORE': ['数码', '电子产品'],
    'APPLE.COM': ['数码', '应用软件'],
    'APPLE': ['数码', '软件'],
    'COCO FRESH TEA': ['餐饮', '饮品'],
    'DAMIAN WARNER': ['运动', '健身'],
    'EMPL INS': ['收入', 'EI'],
    'EUREST': ['餐饮', 'work'],
    'FARM BOY': ['Grocery'],
    'FIDO MOBILE': ['Phone Bill'],
    'IMMIGRATION CANADA': ['政府服务', '移民申请'],
    'JUQU EDUCATION': ['教育', '学费'],
    'JAPANESE CANADI': ['餐饮', '活动餐食'],
    'POPARIDE': ['交通', '拼车'],
    'PREAUTHORIZED PAYMENT': ['转账', '还款'],
    'REXALL PHARMACY': ['购物', '药妆'],
    'SEND E/TFR': ['转账', '电子转账'],
    'SQ *GUSHI EVENT': ['餐饮', '活动'],
    'SQ *NATURALJAPA': ['餐饮', '活动'],
    'SQ *OMUSUBI BAR': ['餐饮', '活动'],
    'SQ *YURURI CRAF': ['餐饮', '活动'],
    'TCKTWEB*HINAMATSURI202': ['娱乐', '门票'],
    'TD MHA PPP': ['转账', '账户转移'],
    'TD VISA PREAUTH PYMT': ['转账', '信用卡还款'],
    'UBER CANADA/UBEREATS': ['餐饮', '外卖'],
    'UBER CANADA/UBERTRIP': ['交通', '打车'],
    'UBER CANADA/UBERCASH': ['交通', '打车'],
    'UBER': ['交通', '打车'],
    'WOBO.AI': ['数码', '应用软件'],
    'TAPNOW.AI': ['数码', 'AI应用软件'],
    'LORAAI.IO': ['数码', 'AI应用软件'],
    'MIDJOURNEY': ['数码', 'AI应用软件'],
    'WHOP*PXLDJO': ['数码', 'AI应用软件'],
    '*RFBT/MARKVILLE MALL': ['购物', '商场'],
    'COMFY.ORG': ['数码', 'AI应用软件'],
    'LUCY': ['餐饮', 'dine in'],
    'SHOPPERS DRUG': ['购物'],
    'MCDONALD': ['餐饮', 'dine in'],
    'MARSHALLS/HOMES': ['购物', '日用'],
    'MEAL': ['餐饮', 'dine in'],
    'WESTERN DRUG MART': ['购物'],
    'IVEY BUSINESS SCHOOL': ['餐饮', 'dine in'],
    'SEPHORA': ['护肤'],
    'TEMU': ['购物'],
    'URBAN PLANET': ['购物'],
    'COCA COLA': ['餐饮', '零食'],
    'OPENAI': ['数码', '应用软件'],
    'WHOLE FOODS': ['Grocery'],
    'XIANG ZI': ['餐饮', 'dine in'],
    'GOOD CATCH BAR': ['餐饮', 'dine in'],
    'PROVIDENT ENERG': ['住房', '水电费'],
    'SQUARE ONE INS': ['住房', '住房保险'],
    'AMZN MKTP CA': ['购物'],
    'HERO TEA LONDON': ['餐饮', '饮品'],
    'SQ *PISTACHIOS ? QUALITY': ['餐饮', '零食'],
    'LONDON MUSLIM MOSQUE': ['慈善', '宗教捐赠'],
    'TST-THAIFOON DOWNTOWN': ['餐饮', '泰餐'],
    'LONDON TRANSIT COMMISS': ['交通', '公交'],
    'TWINS LOUNGE': ['餐饮', '酒吧'],
    'M&M FOOD MARKET #036': ['Grocery'],
    "ANGELO'S ITALIAN MARKE": ['Grocery'],
    'BELL CANADA (OB)': ['Phone Bill'],
    'SQ *TC TRADE GOSQ.COM': ['购物', '二手交易'],
    'SEND E-TFR': ['转账', '电子转账'],
    'MONTHLY ACCOUNT FEE': ['银行', '账户管理费'],
    'ACCT BAL REBATE': ['银行', '账户返利'],
    'BLACK WALNUT BA': ['餐饮', '甜品'],
    'POPEYE': ['餐饮', '快餐'],
    'THE TEA HAUS': ['餐饮', '饮品'],
    'GOLS LANZHOU NOODLE': ['餐饮', '中式'],
    'MOTHER HUBBARDS': ['餐饮', 'dine in'],
    'THE SPOKE': ['餐饮', 'dine in'],
    "SQ *HAVEN'S CRE": ['餐饮', '甜品']
}

df_exp['一级分类'] = df_input['Description'].apply(
    lambda x: next((category_mapping[key][0] for key in category_mapping.keys() if key in str(x).upper()), None)
 )
df_exp['二级分类'] = df_input['Description'].apply(
    lambda x: next((category_mapping[key][1] for key in category_mapping.keys() if key in str(x).upper() and len(category_mapping[key]) > 1), None)
 )

In [23]:
# 1. Create a "mask" (a list of True/False) for rows containing the string
# case=False makes it catch "td mha" or "TD MHA"
mask = df_input['Description'].str.contains("TD MHA", case=False, na=False)

# 2. Update multiple columns for those specific rows in one go
df_exp.loc[mask, ['类型', '账户1', '账户2']] = ["转账", "995", "375"]

In [24]:
df_exp

     日期   类型   金额        一级分类     二级分类  账户1  账户2   备注   货币   标签
0   NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
1   NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN  NaN          餐饮       酒吧  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN          购物       药妆  NaN  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN          交通       公交  NaN  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN          转账       还款  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
11  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
12  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
14  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
15  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
18  NaN  NaN  NaN          餐饮       快餐  NaN  NaN  NaN  NaN  NaN
19  NaN  NaN  NaN          餐饮       外卖  NaN  NaN  NaN  NaN  NaN
20  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
21  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
23  NaN  NaN  NaN          餐饮       中式  NaN  NaN  NaN  NaN  NaN
24  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
25  NaN  NaN  NaN          餐饮       饮品  NaN  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
27  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
28  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
29  NaN  NaN  NaN     Grocery      NaN  NaN  NaN  NaN  NaN  NaN
30  NaN  NaN  NaN          购物       药妆  NaN  NaN  NaN  NaN  NaN
31  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
33  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
34  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
35  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
36  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
37  NaN  NaN  NaN         NaN      NaN  NaN  NaN  NaN  NaN  NaN
38  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
39  NaN  NaN  NaN  Phone Bill      NaN  NaN  NaN  NaN  NaN  NaN
40  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
41  NaN  NaN  NaN          餐饮       中式  NaN  NaN  NaN  NaN  NaN
42  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN

In [25]:


# This covers both actual empty strings and null/NaN values
df_exp['一级分类'] = df_exp['一级分类'].replace(['', np.nan, None], '餐饮')

In [26]:
df_exp

     日期   类型   金额        一级分类     二级分类  账户1  账户2   备注   货币   标签
0   NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
1   NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN  NaN          餐饮       酒吧  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN          购物       药妆  NaN  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN          交通       公交  NaN  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN          转账       还款  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
11  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
12  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
14  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
15  NaN  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
18  NaN  NaN  NaN          餐饮       快餐  NaN  NaN  NaN  NaN  NaN
19  NaN  NaN  NaN          餐饮       外卖  NaN  NaN  NaN  NaN  NaN
20  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
21  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
23  NaN  NaN  NaN          餐饮       中式  NaN  NaN  NaN  NaN  NaN
24  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
25  NaN  NaN  NaN          餐饮       饮品  NaN  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
27  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
28  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
29  NaN  NaN  NaN     Grocery      NaN  NaN  NaN  NaN  NaN  NaN
30  NaN  NaN  NaN          购物       药妆  NaN  NaN  NaN  NaN  NaN
31  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
33  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
34  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
35  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
36  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
37  NaN  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
38  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
39  NaN  NaN  NaN  Phone Bill      NaN  NaN  NaN  NaN  NaN  NaN
40  NaN  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
41  NaN  NaN  NaN          餐饮       中式  NaN  NaN  NaN  NaN  NaN
42  NaN  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN

In [27]:
# Parse mixed date formats in the source file: MM/DD/YYYY, YYYY/MM/DD, and YYYY-MM-DD
parsed_dates = pd.to_datetime(df_input['Date'], format='%m/%d/%Y', errors='coerce')
parsed_dates = parsed_dates.fillna(pd.to_datetime(df_input['Date'], format='%Y/%m/%d', errors='coerce'))
parsed_dates = parsed_dates.fillna(pd.to_datetime(df_input['Date'], format='%Y-%m-%d', errors='coerce'))

if parsed_dates.isna().any():
    invalid_examples = df_input.loc[parsed_dates.isna(), 'Date'].head(5).tolist()
    raise ValueError(f"Unrecognized date format found in Date column: {invalid_examples}")

df_input['Date'] = parsed_dates
df_exp['日期'] = df_input['Date'].dt.strftime('%Y年%m月%d日')

In [28]:
df_exp

             日期   类型   金额        一级分类     二级分类  账户1  账户2   备注   货币   标签
0   2026年05月11日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
1   2026年05月10日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
2   2026年05月08日  NaN  NaN          餐饮       酒吧  NaN  NaN  NaN  NaN  NaN
3   2026年05月07日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
4   2026年05月05日  NaN  NaN          购物       药妆  NaN  NaN  NaN  NaN  NaN
5   2026年05月05日  NaN  NaN          交通       公交  NaN  NaN  NaN  NaN  NaN
6   2026年05月05日  NaN  NaN          转账       还款  NaN  NaN  NaN  NaN  NaN
7   2026年05月03日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
8   2026年05月02日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
9   2026年05月02日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
10  2026年05月02日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
11  2026年05月02日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
12  2026年05月02日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
13  2026年05月01日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
14  2026年05月01日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
15  2026年04月30日  NaN  NaN          数码   AI应用软件  NaN  NaN  NaN  NaN  NaN
16  2026年04月30日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
17  2026年04月30日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
18  2026年04月30日  NaN  NaN          餐饮       快餐  NaN  NaN  NaN  NaN  NaN
19  2026年04月25日  NaN  NaN          餐饮       外卖  NaN  NaN  NaN  NaN  NaN
20  2026年04月24日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
21  2026年04月24日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
22  2026年04月23日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
23  2026年04月23日  NaN  NaN          餐饮       中式  NaN  NaN  NaN  NaN  NaN
24  2026年04月22日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
25  2026年04月21日  NaN  NaN          餐饮       饮品  NaN  NaN  NaN  NaN  NaN
26  2026年04月21日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
27  2026年04月21日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
28  2026年04月21日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
29  2026年04月20日  NaN  NaN     Grocery      NaN  NaN  NaN  NaN  NaN  NaN
30  2026年04月20日  NaN  NaN          购物       药妆  NaN  NaN  NaN  NaN  NaN
31  2026年04月19日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
32  2026年04月18日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
33  2026年04月18日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
34  2026年04月17日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
35  2026年04月17日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
36  2026年04月17日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
37  2026年04月17日  NaN  NaN          餐饮      NaN  NaN  NaN  NaN  NaN  NaN
38  2026年04月16日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN
39  2026年04月16日  NaN  NaN  Phone Bill      NaN  NaN  NaN  NaN  NaN  NaN
40  2026年04月16日  NaN  NaN          交通       打车  NaN  NaN  NaN  NaN  NaN
41  2026年04月15日  NaN  NaN          餐饮       中式  NaN  NaN  NaN  NaN  NaN
42  2026年04月14日  NaN  NaN          餐饮  dine in  NaN  NaN  NaN  NaN  NaN

In [29]:
# Initialize columns
df_exp['金额'] = df_input['Amount_2']
df_exp['类型'] = "收入"

# Update rows where Amount_1 has data
mask = (df_input['Amount_1'].fillna('') != '')
df_exp.loc[mask, '金额'] = df_input['Amount_1']
df_exp.loc[mask, '类型'] = "支出"

In [30]:
df_exp['备注'] = df_input['Description']
# df_exp['金额'] = df_input['Amount']
# df_exp['类型'] = df_input['Category'].map(transaction_mapping)
# df_exp['类型'].fillna("支出", inplace=True)
# df_exp['账户1'] = df_input['Account Name'].map(account_mapping)

df_exp['货币'] = 'CAD'

In [31]:
df_exp.to_csv('export.csv', index=False)

In [32]:
df_exp

,日期,类型,金额,一级分类,二级分类,账户1,账户2,备注,货币,标签
0,2026年05月11日,支出,48.57,餐饮,NaN,NaN,NaN,OZEN KOREA,CAD,NaN
1,2026年05月10日,支出,4.75,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
2,2026年05月08日,支出,9.04,餐饮,酒吧,NaN,NaN,TWINS LOUNGE,CAD,NaN
3,2026年05月07日,支出,159.08,餐饮,dine in,NaN,NaN,FACTOR MEALS,CAD,NaN
4,2026年05月05日,支出,32.52,购物,药妆,NaN,NaN,REXALL PHARMACY #1790,CAD,NaN
5,2026年05月05日,支出,50.00,交通,公交,NaN,NaN,LONDON TRANSIT COMMISS,CAD,NaN
6,2026年05月05日,收入,664.99,转账,还款,NaN,NaN,PREAUTHORIZED PAYMENT,CAD,NaN
7,2026年05月03日,支出,501.77,数码,AI应用软件,NaN,NaN,TAPNOW.AI,CAD,NaN
8,2026年05月02日,支出,309.75,餐饮,NaN,NaN,NaN,PROMETRIC.COM,CAD,NaN
9,2026年05月02日,支出,309.75,餐饮,NaN,NaN,NaN,PROMETRIC.COM,CAD,NaN
10,2026年05月02日,支出,70.53,数码,AI应用软件,NaN,NaN,LORAAI.IO,CAD,NaN
11,2026年05月02日,支出,13.99,数码,AI应用软件,NaN,NaN,LORAAI.IO,CAD,NaN
12,2026年05月02日,支出,13.99,数码,AI应用软件,NaN,NaN,LORAAI.IO,CAD,NaN
13,2026年05月01日,支出,35.10,数码,AI应用软件,NaN,NaN,WHOP*PXLDJO,CAD,NaN
14,2026年05月01日,支出,140.37,数码,AI应用软件,NaN,NaN,COMFY.ORG,CAD,NaN
15,2026年04月30日,支出,15.89,数码,AI应用软件,NaN,NaN,MIDJOURNEY INC.,CAD,NaN
16,2026年04月30日,支出,148.16,餐饮,dine in,NaN,NaN,FACTOR MEALS,CAD,NaN
17,2026年04月30日,支出,12.45,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
18,2026年04月30日,支出,2.09,餐饮,快餐,NaN,NaN,POPEYE'S #13585,CAD,NaN
19,2026年04月25日,支出,106.48,餐饮,外卖,NaN,NaN,UBER CANADA/UBEREATS,CAD,NaN
20,2026年04月24日,支出,9.72,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
21,2026年04月24日,支出,4.24,餐饮,NaN,NaN,NaN,SQ *LOCOMOTIVE ESPRESSO,CAD,NaN
22,2026年04月23日,支出,143.49,餐饮,dine in,NaN,NaN,FACTOR MEALS,CAD,NaN
23,2026年04月23日,支出,23.71,餐饮,中式,NaN,NaN,GOLS LANZHOU NOODLE,CAD,NaN
24,2026年04月22日,支出,4.00,餐饮,NaN,NaN,NaN,SQ *LONDON BICYCLE CAFE,CAD,NaN
25,2026年04月21日,支出,6.24,餐饮,饮品,NaN,NaN,THE TEA HAUS,CAD,NaN
26,2026年04月21日,支出,14.34,餐饮,NaN,NaN,NaN,SEOUL SEAFOOD SHOPPE,CAD,NaN
27,2026年04月21日,支出,7.79,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
28,2026年04月21日,支出,9.90,餐饮,NaN,NaN,NaN,SQ *SIDETRACK: A WORTLEY,CAD,NaN
29,2026年04月20日,支出,57.64,Grocery,NaN,NaN,NaN,FARM BOY #93,CAD,NaN
30,2026年04月20日,支出,7.90,购物,药妆,NaN,NaN,REXALL PHARMACY #1790,CAD,NaN
31,2026年04月19日,支出,9.84,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
32,2026年04月18日,支出,16.95,餐饮,dine in,NaN,NaN,MOTHER HUBBARDS RESTAU,CAD,NaN
33,2026年04月18日,支出,5.65,餐饮,dine in,NaN,NaN,MOTHER HUBBARDS RESTAU,CAD,NaN
34,2026年04月17日,支出,9.34,交通,打车,NaN,NaN,UBER CANADA/UBERTRIP,CAD,NaN
35,2026年04月17日,支出,14.68,餐饮,NaN,NaN,NaN,SQ *SIDETRACK: A WORTLEY,CAD,NaN
36,2026年04月17日,支出,10.32,餐饮,NaN,NaN,NaN,SQ *SIDETRACK: A WORTLEY,CAD,NaN
37,2026年04月17日,支出,10.45,餐饮,NaN,NaN,NaN,SQ *MORNINGSTAR'S,CAD,NaN
38,2026年04月16日,支出,93.53,餐饮,dine in,NaN,NaN,FACTOR MEALS,CAD,NaN
39,2026年04月16日,收入,8.47,Phone Bill,NaN,NaN,NaN,BELL CANADA (OB),CAD,NaN
40,2026年04月16日,支出,30.00,交通,打车,NaN,NaN,UBER CANADA/UBERCASH,CAD,NaN
41,2026年04月15日,支出,19.20,餐饮,中式,NaN,NaN,GOLS LANZHOU NOODLE,CAD,NaN
42,2026年04月14日,支出,17.84,餐饮,dine in,NaN,NaN,THE SPOKE,CAD,NaN